### ISSUE TITLE
Using Docker Compose on M1 Mac - 

### ISSUE THREAD

**Issue by musicjunkieg** [docker/getting-started#229]
When running the docker-compose.yaml file, I get the following error when running **docker-compose up -d**:

"bryanguffey@Bryans-Mac-mini app % docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.volumes: 'todo-mysql-data'"

Here is my compose file:

`version: "3.8"

services:
  app:
    image: node:12-alpine
    command: sh -c "apk --no-cache --virtual build-dependencies add python2 make g++ && yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes: 
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  volumes:
    todo-mysql-data:
`

I have tried this with both version 3.7 and 3.8 schemas. This is exactly what is in the tutorial, and exactly what is even in the spec. VS Code keeps saying that the property todo-mysql-data is not allowed on the second to last line. 

Please help! M1 Mac mini running Monterey 12.0.1

**Comment by vignemail1** [comment]
Can you reformat your posted compose file, it is impossible to diagnose without indentation?

**Comment by StefanScherer** [comment]
@musicjunkieg Indentation of a YAML file is very important and often leads to problems if it's not correct. Your docker-compose.yml should look like this to make it work:

```yaml
version: "3.8"

services:
  app:
    image: node:12-alpine
    command: sh -c "apk --no-cache --virtual build-dependencies add python2 make g++ && yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
```
