### ISSUE TITLE
Timeout before mysql is launched with docker-compose

### ISSUE THREAD

**Issue by colios13** [docker/getting-started#351]
Since this [commit](https://github.com/docker/getting-started/commit/8dff10bcaace379a18b70fda8a49238e8c0e20f9) which add a timeout an older [issue](https://github.com/docker/getting-started/issues/48) is back.

The timeout was removed because it was creating a problem with slow/busy machine which wasn't able to have the mysql container ready before the timeout (which was 15s at that time). In my case I have experiencing the same issue my mysql container take a bit more than 2min to be fully ready.

### Suggestions

Put a much longer timeout, or use the [depends_on](https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-1) condition with the [healthcheck](https://github.com/compose-spec/compose-spec/blob/master/spec.md#healthcheck) instruction in the docker-compose.yaml for example:
```
  app:
    ...
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    ...
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 40
```
(This will take a bit more time than the longer timeout solution because the app container will wait the mysql container to be fully ready before starting)

PS: Also wondering how this can take 2min for me (with 8Go RAM and an i5-4210H CPU @ 2.90GHz × 4) when for other people it's look like to take less than 10s.
