### ISSUE TITLE
Cannot Umount Directory From Host To Container

### ISSUE THREAD

**Issue by YovanggaAnandhika** [docker/getting-started#443]
I build compose.yml for buil container with nodejs official from strach
but all file to packages/frontend cannot read from container.

With error logs like this :

```
024-06-24 14:17:20 yarn run v1.22.22
2024-06-24 14:17:20 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2024-06-24 14:17:20 error Couldn't find a package.json file in "/home/app"
```

the code :

````
name: dev-syncmed-klinik

services:
  #
  dev-frontend-node:
    image: node:alpine
    container_name: dev-frontend
    working_dir: /home/app
    volumes:
      - ./packages/frontend:/home/app # Adjust path if needed
    networks:
      dev-syncmed-network:
        ipv4_address: 101.113.0.2
    ports:
      - "80:80"
    command: "yarn run start"

  dev-backend-node:
    image: node:alpine
    container_name: dev-backend
    working_dir: /home/app
    volumes:
      - ./packages/backend:/home/app # Adjust path if needed
      - test-data:/home/app
    links:
      - dev-mongodb
    networks:
      dev-syncmed-network:
        ipv4_address: 101.113.0.3
    ports:
      - "5000:5000"
    command: "yarn run start"
    depends_on:
      - dev-mongodb


  dev-mongodb:
    image: mongo:latest
    container_name: dev-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: -
      MONGO_INITDB_ROOT_PASSWORD: -
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      dev-syncmed-network:
        ipv4_address: 101.113.0.4

volumes:
  mongodb-data:
    name: dev-mongodb
    driver: local
  test-data:
    driver: local

networks:
  dev-syncmed-network:
    driver: bridge
    ipam:
      config:
        - subnet: 101.113.0.0/24

````
